<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%@ taglib prefix="c" uri="jakarta.tags.core" %>
<!DOCTYPE html><html lang="vi"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0">
<title>Email kết quả xét duyệt - IMS</title><link rel="stylesheet" href="${pageContext.request.contextPath}/frontend/css/dashboard.css?v=20261007-3"><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css">
<style>.mail-status{display:inline-flex;padding:5px 9px;border-radius:999px;font-size:11px;font-weight:800}.mail-status.SENT{background:#def7ec;color:#18794e}.mail-status.PENDING,.mail-status.PROCESSING{background:#fff4d6;color:#996515}.mail-status.FAILED,.mail-status.FAILED_FINAL{background:#fde8e8;color:#b42318}.mail-note{max-width:290px;white-space:normal;color:var(--text-muted);font-size:12px}.config-alert{padding:13px 16px;margin-bottom:18px;border-radius:9px;background:#fff8e6;border:1px solid #f1d694;color:#805b10}.queue-toolbar{display:flex;justify-content:space-between;align-items:center;gap:15px;margin-bottom:18px}.queue-toolbar p{margin:0;color:var(--text-muted)}</style></head>
<body><div class="layout"><aside class="sidebar"><div class="logo"><div class="logo-icon"><i class="fa-solid fa-user-tie"></i></div><div><h2>IMS Portal</h2><span>Phòng Nhân sự (HR)</span></div></div><nav class="menu"><p class="menu-title">NGHIỆP VỤ HR</p><a href="${pageContext.request.contextPath}/home" class="menu-item"><i class="fa-solid fa-chart-line"></i><span>Dashboard HR</span></a><a href="${pageContext.request.contextPath}/documents/review" class="menu-item"><i class="fa-solid fa-file-circle-check"></i><span>Duyệt tài liệu &amp; CV</span></a><a href="${pageContext.request.contextPath}/review-emails" class="menu-item active"><i class="fa-solid fa-envelope-circle-check"></i><span>Email kết quả</span></a></nav><div class="sidebar-bottom"><a href="${pageContext.request.contextPath}/logout" class="menu-item logout"><i class="fa-solid fa-right-from-bracket"></i><span>Đăng xuất</span></a></div></aside>
<main class="main"><header class="header"><div class="search-box"><i class="fa-solid fa-magnifying-glass"></i><input type="text" placeholder="Tìm email người nhận..."></div></header><section class="content"><div class="page-title"><div><h1><i class="fa-solid fa-envelope-circle-check" style="color:var(--action-accent);margin-right:10px"></i>Email kết quả xét duyệt</h1><p>Theo dõi email chờ gửi, đã gửi và gửi lỗi.</p></div></div>
<c:if test="${not smtpConfigured}"><div class="config-alert"><i class="fa-solid fa-triangle-exclamation"></i> SMTP chưa được cấu hình. Hãy thiết lập <strong>IMS_SMTP_USER</strong> và <strong>IMS_SMTP_PASSWORD</strong>; email vẫn được giữ an toàn trong hàng đợi.</div></c:if>
<c:if test="${not empty param.processed}"><div class="config-alert" style="background:#edf9f2;border-color:#b7e4c7;color:#18794e">Đã gửi thành công ${param.processed} email đến hạn.</div></c:if>
<div class="queue-toolbar"><p>Lịch gửi hằng ngày: <strong>${sendHour}:00</strong> · Tối đa 200 bản ghi gần nhất</p><form method="post"><button class="primary-btn" type="submit"><i class="fa-solid fa-paper-plane"></i> Gửi các email đến hạn</button></form></div>
<div class="card"><div class="table-container"><table><thead><tr><th>Người nhận</th><th>Hồ sơ</th><th>Kết quả</th><th>Dự kiến gửi</th><th>Trạng thái</th><th>Lần thử</th><th>Thông tin lỗi</th></tr></thead><tbody><c:forEach items="${jobs}" var="job"><tr><td><strong>${job.recipientName}</strong><small style="display:block;color:var(--text-muted)">${job.recipientEmail}</small></td><td>${job.documentName}</td><td><span class="badge ${job.decision == 'APPROVED' ? 'active' : 'inactive'}">${job.decision == 'APPROVED' ? 'Đã duyệt' : 'Từ chối'}</span><c:if test="${not empty job.rejectionReason}"><small style="display:block;margin-top:4px">${job.rejectionReason}</small></c:if></td><td>${job.scheduledAt}</td><td><span class="mail-status ${job.status}">${job.status}</span></td><td>${job.attemptCount}</td><td class="mail-note">${empty job.lastError ? '-' : job.lastError}</td></tr></c:forEach><c:if test="${empty jobs}"><tr><td colspan="7" style="padding:42px;text-align:center;color:var(--text-muted)"><i class="fa-regular fa-envelope" style="font-size:25px"></i><p>Chưa có email kết quả nào trong hàng đợi.</p></td></tr></c:if></tbody></table></div></div></section></main></div></body></html>
